# Generated by Django 3.2.8 on 2021-10-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportClubApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_usuario',
            new_name='id',
        ),
    ]
